# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4f18bba3722d63c58c7fa335ef92a4e753e988bc1602e70d09fbb2140e4a0ec3c60d0920a0fd4f1923ad80f9b62f6c271949ceb66fbc79b1ae6c89895bf21b

test:
  secret_key_base: 8e48255f5bd5c251ae07267b43d5ef9934fcd95d2f6167122c46841fe84025e931dfc027b4603791434f0b0f2e48f2009fe47ba5bb5983de023a160b0a5cff39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
